### ISSUE TITLE
emptyBuilder

### ISSUE THREAD

**Issue by YingChangJ** [krymlov/swe-jni-lib#1]
Hello Krymlov,

I've encountered an issue with the JNI library when using emptyBuilder. It appears that this function is causing my app to crash, particularly when swe_fixstar() is called. Following some advice from ChatGPT, I replaced CallObjectMethod with CallVoidMethod, and that seems to have resolved the problem.

I'm not entirely sure if this issue is specific to my environment (I'm using Kotlin here). If it works fine in Java, you can disregard this matter.

Best regards,
```
void emptyBuilder(JNIEnv *env, jobject builder) {
    if (NULL == builder) return;

    // Obtain the Java StringBuilder class handle
    jclass clazz = (*env)->GetObjectClass(env, builder);
    // Obtain the method ID for the StringBuilder setLength method
    jmethodID mid = (*env)->GetMethodID(env, clazz, "setLength", "(I)V");
    // If this method does not exist then return.
    if (mid == 0) return;
    // Call the StringBuilder object's setLength method
    //(*env)->CallObjectMethod(env, builder, mid, 0);
    (*env)->CallVoidMethod(env, builder, mid, 0);
}
```

**Comment by krymlov** [comment]
Hi YingChangJ !

thanks, i will use CallVoidMethod instead of CallObjectMethod
