### ISSUE TITLE
Facing issue while creating .so file 

### ISSUE THREAD

**Issue by ndbond1630** [krymlov/swe-jni-lib#2]
Dear Team,
I am facing below error while trying to build and create .so file of this project so, I can use native library to use swe library in my java program on Mac machine. 

>>> swe-jni-lib-main $ cmake . /Users/****/Documents/Learning/Microservices/swe-jni-lib-main

-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/****/Documents/Learning/Microservices/swe-jni-lib-main
>>> swe-jni-lib-main $ make
[  9%] Building C object CMakeFiles/swe-2.10.03j3d.dir/src/swecl.c.o
[ 18%] Building C object CMakeFiles/swe-2.10.03j3d.dir/src/swedate.c.o
[ 27%] Building C object CMakeFiles/swe-2.10.03j3d.dir/src/swehel.c.o
[ 36%] Building C object CMakeFiles/swe-2.10.03j3d.dir/src/swehouse.c.o
[ 45%] Building C object CMakeFiles/swe-2.10.03j3d.dir/src/swejni.c.o
In file included from /Users/****/Documents/Learning/Microservices/swe-jni-lib-main/src/swejni.c:8:
In file included from /Users/****/Documents/Learning/Microservices/swe-jni-lib-main/src/swejni.h:2:
/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
         ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/swe-2.10.03j3d.dir/src/swejni.c.o] Error 1
make[1]: *** [CMakeFiles/swe-2.10.03j3d.dir/all] Error 2
make: *** [all] Error 2

Please let me know if I am missing something or following any incorrect step.

Thanks,
~ Nishant

**Comment by krymlov** [comment]
> /Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
this error has no relation to the project, please make sure jni_md.h is located where it should be - this is JDK related header file
try to google this issue, there is many topics about it...
